export default {
  "/": ["*"],
  "/bill-of-lading/inputs": [
    "weighbridgeAdmin",
    "weighbridgeUser",
    "statistics&InformationUser",
    "transportUser",
    "domesticTruckSupervisor",
  ],
  "/bill-of-lading/bulk-outputs": [
    "weighbridgeAdmin",
    "weighbridgeUser",
    "statistics&InformationUser",
    "transportUser",
    "domesticTruckSupervisor",
  ],
  "/bill-of-lading/pier": [
    "weighbridgeAdmin",
    "weighbridgeUser",
    "statistics&InformationUser",
    "transportUser",
    "domesticTruckSupervisor",
  ],
  "/bill-of-lading/contract-remaining": ["weighbridgeAdmin"],
  "/security-turning": ["securityAgent", "weighbridgeAdmin"],
  // '/bill-of-lading/input-report': ['weighbridgeAdmin', 'weighbridgeUser'],
  // '/bill-of-lading/bulk-output-report': ['weighbridgeAdmin', 'weighbridgeUser'],
  // '/bill-of-lading/pier-report': ['weighbridgeAdmin', 'weighbridgeUser'],
  "/bill-of-lading/north-refinery-to-aor-outputs": [
    "weighbridgeAdmin",
    "weighbridgeUser",
    "statistics&InformationUser",
    "domesticTruckSupervisor",
  ],
  "/bill-of-lading/resources-list": [
    "weighbridgeAdmin",
    "weighbridgeUser",
    "statistics&InformationUser",
  ],
  "/bill-of-lading/security-acceptance-report": [
    "weighbridgeAdmin",
    "weighbridgeUser",
  ],
  "/bill-of-lading/weighbridge-leaving": [
    "weighbridgeAdmin",
    "weighbridgeUser",
  ],
  "/bill-of-lading/login-to-scale": ["weighbridgeAdmin", "weighbridgeUser"],
  "/resources/products": [
    "weighbridgeAdmin",
    "weighbridgeUser",
    "weighbridgeAdmin",
    "statistics&InformationUser",
  ],
  "/resources/transport-contractors": [
    "weighbridgeAdmin",
    "weighbridgeUser",
    "weighbridgeAdmin",
    "statistics&InformationUser",
  ],
  "/resources/refineries": [
    "statistical&InformationUser",
    "weighbridgeAdmin",
    "weighbridgeUser",
    "statistics&InformationUser",
  ],
  "/resources/origin-tanks": [
    "statistical&InformationUser",
    "weighbridgeAdmin",
    "weighbridgeUser",
    "statistics&InformationUser",
  ],
  "/resources/drain-tanks": [
    "statistical&InformationUser",
    "weighbridgeAdmin",
    "weighbridgeUser",
    "statistics&InformationUser",
  ],
  "/resources/destinations": [
    "statistical&InformationUser",
    "weighbridgeAdmin",
    "weighbridgeUser",
    "statistics&InformationUser",
  ],
  "/resources/buyers": [
    "statistical&InformationUser",
    "weighbridgeAdmin",
    "statistics&InformationUser",
  ],
  "/bill-of-lading/tanker-info": ["weighbridgeAdmin", "weighbridgeUser"],
  "/bill-of-lading/share": ["weighbridgeAdmin", "weighbridgeUser"],
  // '/transport/driver': ['transportUser', 'transportManager', 'transportSupervisor', 'domesticTruckSupervisor'],
  "/transport/drivers": [
    "transportUser",
    "transportManager",
    "transportSupervisor",
    "domesticTruckSupervisor",
  ],
  // '/transport/owner': ['transportUser', 'transportManager', 'transportSupervisor', 'domesticTruckSupervisor'],
  "/transport/owners": [
    "transportUser",
    "transportManager",
    "transportSupervisor",
    "domesticTruckSupervisor",
  ],
  "/transport/evaluation": [
    "transportUser",
    "transportManager",
    "transportSupervisor",
    "netSupervisor",
    "transportOperation",
    "domesticTruckSupervisor",
  ],
  "/transport/evaluate": [
    "transportUser",
    "transportManager",
    "transportSupervisor",
    "netSupervisor",
    "transportOperation",
    "domesticTruckSupervisor",
  ],
  "/transport/contractors": [
    "transportUser",
    "transportManager",
    "transportSupervisor",
    "netSupervisor",
    "transportOperation",
    "domesticTruckSupervisor",
  ],
  "/transport/drivers-scoring-definition": [
    "transportUser",
    "transportManager",
    "transportSupervisor",
    "netSupervisor",
    "transportOperation",
    "domesticTruckSupervisor",
  ],
  "/transport/evaluation-questions": [
    "transportUser",
    "transportManager",
    "transportSupervisor",
    "domesticTruckSupervisor",
  ],
  "/users": ["weighbridgeAdmin"],
  "/security/oil-material-turning": ["weighbridgeAdmin"],
  "/security/other-material-turning": ["weighbridgeAdmin"],
};
